import React, { useState } from 'react';
import { 
  X, 
  Search, 
  BookOpen, 
  CheckCircle2, 
  Zap, 
  Droplets, 
  Flame, 
  Activity, 
  DollarSign, 
  ShieldCheck,
  HelpCircle,
  Sparkles
} from 'lucide-react';

interface GlossaryTerm {
  term: string;
  shortName: string;
  category: 'Oil & Gas' | 'Power Plant' | 'Finance & Health' | 'General';
  simpleMeaning: string;
  whyItMatters: string;
  exampleValue: string;
}

const GLOSSARY_TERMS: GlossaryTerm[] = [
  // Oil & Gas
  {
    term: 'bbl/d (Barrels per Day)',
    shortName: 'bbl/d',
    category: 'Oil & Gas',
    simpleMeaning: 'The standard measurement of crude oil volume pumped per day. One barrel is 42 US gallons (about 159 liters).',
    whyItMatters: 'This is the primary revenue metric for an oil platform. More barrels per day = higher production income.',
    exampleValue: '84,200 bbl/d is the daily output of FPSO Leviathan Alpha.'
  },
  {
    term: 'MMscf/d (Million Standard Cubic Feet per Day)',
    shortName: 'MMscf/d',
    category: 'Oil & Gas',
    simpleMeaning: 'The volume of natural gas produced and piped away every 24 hours.',
    whyItMatters: 'Gas is separated from oil. Exporting it earns revenue; wasting or leaking it causes pollution and fines.',
    exampleValue: '148.0 MMscf/d exported into the subsea pipeline.'
  },
  {
    term: 'RUL (Remaining Useful Life)',
    shortName: 'RUL',
    category: 'Finance & Health',
    simpleMeaning: 'An AI-predicted health score (0% to 100%) showing how much longer a machine can run safely before it needs service.',
    whyItMatters: 'Above 80% = Healthy. Below 70% = Plan maintenance now before the machine breaks unexpectedly.',
    exampleValue: 'Compressor K-101 has 74% RUL (18 days remaining before required seal replacement).'
  },
  {
    term: 'PIG & Pig Launcher (Pipeline Inspection Gauge)',
    shortName: 'PIG',
    category: 'Oil & Gas',
    simpleMeaning: 'An automated internal pipe-cleaning and ultrasound robot that is pushed through undersea pipelines by oil pressure to scrape dirt and check for metal cracks.',
    whyItMatters: 'Prevents underwater pipeline blockages and bursts without needing human divers.',
    exampleValue: '16" Intelligent Caliper Pig launched every 90 days.'
  },
  {
    term: 'BSW (Basic Sediment and Water)',
    shortName: 'BSW',
    category: 'Oil & Gas',
    simpleMeaning: 'The percentage of dirty sand and salty seawater mixed in with the crude oil coming out of the ground.',
    whyItMatters: 'Refineries only accept clean oil (under 0.5% BSW). The platform must filter out water before shipping.',
    exampleValue: 'Subsea Well #1 has 4.8% BSW before separator filtering.'
  },
  {
    term: 'Ullage (Storage Headroom)',
    shortName: 'Ullage',
    category: 'Oil & Gas',
    simpleMeaning: 'The empty space left at the top of an oil cargo tank before it is completely 100% full.',
    whyItMatters: 'Tells the control room how many more days of oil they can store before a shuttle tanker ship must arrive.',
    exampleValue: '470,000 bbl in tanks = 530,000 bbl ullage (room left).'
  },
  {
    term: 'PTW (Permit to Work)',
    shortName: 'PTW',
    category: 'Finance & Health',
    simpleMeaning: 'A mandatory safety certificate and checklist signed by the offshore safety officer before technicians can open pipes or touch heavy machinery.',
    whyItMatters: 'Ensures equipment is depressurized and powered off so workers do not get hurt.',
    exampleValue: 'Cold Work Permit required for dry gas seal inspection.'
  },
  {
    term: 'Metocean (Meteorological & Ocean Conditions)',
    shortName: 'Metocean',
    category: 'Oil & Gas',
    simpleMeaning: 'Real-time weather data at sea: ocean wave height, wave period, and wind speed.',
    whyItMatters: 'Rough seas (waves over 3.5m) make shuttle tanker docking and crane lifts unsafe.',
    exampleValue: '1.8m wave height (Calm sea) • 14 knots wind.'
  },
  {
    term: 'CO₂e (Carbon Dioxide Equivalent)',
    shortName: 'CO₂e',
    category: 'Finance & Health',
    simpleMeaning: 'The standard measurement of greenhouse gas emissions. It combines CO2 and methane into a single pollution score.',
    whyItMatters: 'Government regulations and carbon taxes penalize platforms that emit too much CO2e.',
    exampleValue: '1,248 Tonnes CO2e produced today across generators and flare.'
  },
  // Power Plant
  {
    term: 'MW (Megawatts of Electric Power)',
    shortName: 'MW',
    category: 'Power Plant',
    simpleMeaning: 'The rate of electrical energy produced. 1 Megawatt (MW) powers approximately 750 to 1,000 average homes.',
    whyItMatters: 'This is the primary output of the power station sent to the public grid.',
    exampleValue: '462 MW currently generated by 2 Gas Turbines + 1 Steam Turbine.'
  },
  {
    term: 'Heat Rate (Fuel Efficiency)',
    shortName: 'Heat Rate',
    category: 'Power Plant',
    simpleMeaning: 'How much fuel heat energy (in BTUs) the plant must burn to generate 1 kilowatt-hour (kWh) of electricity. Lower is better!',
    whyItMatters: 'A lower heat rate means the plant is efficient and burns less fuel. A higher heat rate wastes money.',
    exampleValue: '6,820 BTU/kWh (+120 above optimal design, costing $380/hr extra in fuel).'
  },
  {
    term: 'LMP (Locational Marginal Price)',
    shortName: 'LMP',
    category: 'Finance & Health',
    simpleMeaning: 'The wholesale market price paid for 1 Megawatt-hour of electricity at the local grid substation.',
    whyItMatters: 'When electricity prices spike in the evening, every extra megawatt generated earns huge profit.',
    exampleValue: 'Current price: $42/MWh. Peak forecast: $145/MWh at 17:30.'
  },
  {
    term: 'Exhaust Temperature Spread',
    shortName: 'EGT Spread',
    category: 'Power Plant',
    simpleMeaning: 'The difference in hot exhaust gas temperature between the various combustion chambers around a jet turbine.',
    whyItMatters: 'If one chamber is much hotter than the others, it means a fuel nozzle is clogged or damaged.',
    exampleValue: '26°C spread (Target is under 18°C) flags fuel nozzle #4 for cleaning.'
  }
];

interface PlainEnglishModalProps {
  isOpen: boolean;
  onClose: () => void;
  defaultCategory?: string;
}

export const PlainEnglishModal: React.FC<PlainEnglishModalProps> = ({
  isOpen,
  onClose,
  defaultCategory = 'all'
}) => {
  const [search, setSearch] = useState('');
  const [selectedCategory, setSelectedCategory] = useState(defaultCategory);

  if (!isOpen) return null;

  const filtered = GLOSSARY_TERMS.filter(item => {
    const matchCat = selectedCategory === 'all' || item.category === selectedCategory;
    const matchSearch = 
      item.term.toLowerCase().includes(search.toLowerCase()) ||
      item.simpleMeaning.toLowerCase().includes(search.toLowerCase()) ||
      item.shortName.toLowerCase().includes(search.toLowerCase());
    return matchCat && matchSearch;
  });

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-fadeIn">
      <div 
        className="w-full max-w-3xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh] text-slate-900 dark:text-slate-100"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-5 border-b border-slate-100 dark:border-slate-700 flex items-center justify-between bg-gradient-to-r from-blue-50/80 to-indigo-50/50 dark:from-slate-800 dark:to-slate-800">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-blue-600 flex items-center justify-center text-white shadow-sm">
              <BookOpen className="h-5 w-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base sm:text-lg font-bold">
                  Plain-English Terms & Jargon Buster
                </h3>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-blue-500/10 text-blue-700 dark:text-blue-300 border border-blue-500/20">
                  Easy Read Mode
                </span>
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                Simple explanations of technical acronyms, engineering metrics, and AI insights.
              </p>
            </div>
          </div>

          <button 
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-700 transition cursor-pointer"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Search & Category Filter Bar */}
        <div className="p-4 border-b border-slate-100 dark:border-slate-700/80 bg-slate-50/60 dark:bg-slate-800/60 flex flex-col sm:flex-row gap-3">
          <div className="relative flex-1">
            <Search className="h-4 w-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search term or acronym (e.g. RUL, bbl/d, Heat Rate, PIG)..."
              className="w-full pl-9 pr-3 py-2 text-xs bg-white dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div className="flex items-center gap-1 overflow-x-auto text-xs">
            {['all', 'Oil & Gas', 'Power Plant', 'Finance & Health'].map((cat) => (
              <button
                key={cat}
                onClick={() => setSelectedCategory(cat)}
                className={`px-3 py-1.5 rounded-xl font-medium transition whitespace-nowrap cursor-pointer ${
                  selectedCategory === cat
                    ? 'bg-blue-600 text-white shadow-xs'
                    : 'bg-white dark:bg-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-100 border border-slate-200 dark:border-slate-600'
                }`}
              >
                {cat === 'all' ? 'All Terms' : cat}
              </button>
            ))}
          </div>
        </div>

        {/* Terms List */}
        <div className="p-5 overflow-y-auto space-y-4 flex-1">
          {filtered.length === 0 ? (
            <div className="text-center py-12 text-slate-400 text-xs">
              No matching terms found for &quot;{search}&quot;. Try searching for &quot;oil&quot;, &quot;efficiency&quot;, or &quot;health&quot;.
            </div>
          ) : (
            filtered.map((item) => (
              <div 
                key={item.term}
                className="p-4 rounded-xl bg-white dark:bg-slate-800/90 border border-slate-200 dark:border-slate-700 shadow-xs hover:border-blue-400 dark:hover:border-blue-500 transition space-y-2.5"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <span className="font-bold text-sm text-slate-900 dark:text-slate-100">
                      {item.term}
                    </span>
                    <span className="ml-2 text-[10px] uppercase font-semibold px-2 py-0.5 rounded-md bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300">
                      {item.category}
                    </span>
                  </div>
                  <span className="font-mono text-xs font-bold text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-950/40 px-2 py-0.5 rounded border border-blue-200 dark:border-blue-800">
                    {item.shortName}
                  </span>
                </div>

                <div className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed bg-slate-50 dark:bg-slate-900/40 p-2.5 rounded-lg border border-slate-100 dark:border-slate-800">
                  <strong className="text-slate-900 dark:text-slate-100 block mb-0.5 font-semibold">
                    💡 What it means in simple English:
                  </strong>
                  {item.simpleMeaning}
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs pt-1">
                  <div className="text-slate-600 dark:text-slate-400">
                    <span className="font-semibold text-slate-800 dark:text-slate-200">Why it matters: </span>
                    {item.whyItMatters}
                  </div>
                  <div className="text-slate-600 dark:text-slate-400">
                    <span className="font-semibold text-slate-800 dark:text-slate-200">Example in app: </span>
                    <span className="font-mono text-[11px] text-blue-600 dark:text-blue-400">{item.exampleValue}</span>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Footer */}
        <div className="p-3.5 bg-slate-50 dark:bg-slate-800/90 border-t border-slate-100 dark:border-slate-700 flex items-center justify-between text-xs text-slate-500 dark:text-slate-400">
          <span className="flex items-center gap-1.5">
            <Sparkles className="h-3.5 w-3.5 text-blue-600" />
            Plain-English mode is active across all dashboard charts and AI suggestions.
          </span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-xl font-bold bg-blue-600 text-white hover:bg-blue-500 transition cursor-pointer"
          >
            Got It
          </button>
        </div>
      </div>
    </div>
  );
};
